# Generated by Django 2.1.3 on 2018-11-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecompany',
            old_name='is_default_company',
            new_name='is_default',
        ),
        migrations.RemoveField(
            model_name='role',
            name='groups',
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='trading.Company'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_company', to='trading.Role'),
        ),
    ]
