# Generated by Django 2.1.3 on 2018-11-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='products',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='company',
        ),
    ]
