# Generated by Django 2.1.3 on 2018-11-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('trading', '0002_auto_20181126_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(related_name='roles', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='trading.Company'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
