# Generated by Django 2.1.3 on 2018-11-23 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0004_auto_20181123_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(1, 'superadmin'), (2, 'admin'), (3, 'manager'), (4, 'seller'), (5, 'financier')])),
                ('is_default_company', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='employeecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Company'),
        ),
        migrations.AddField(
            model_name='employeecompany',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='employeecompany',
            unique_together={('company', 'employee')},
        ),
    ]
